name: CI

env:
  MIN_SUPPORTED_RUST_VERSION: "1.54.0"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: Build RustDesk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal # minimal component installation (ie, no documentation)
        components: clippy, rustfmt

    - name: Ensure `cargo fmt` has been run
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    - name: Run clippy (on minimum supported rust version to prevent warnings we can't fix)
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --locked --all-targets --all-features

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --locked

    - name: Run build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

